name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    runs-on: ubuntu-latest
    environment: release
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - run: npm ci
      - run: npm run typecheck
      - run: npm run lint
      - run: npm run package
      - name: Publish to VS Code Marketplace
        run: npx vsce publish --no-dependencies --pat ${{ secrets.VSCE_PAT }}
      - name: Publish to Open VSX
        run: npx ovsx publish --pat ${{ secrets.OVSX_PAT }}
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: "*.vsix"
